### ISSUE TITLE
Cannot find Stationery options

### ISSUE THREAD

**Issue by jefferyto** [arivald/tbirdExt#4]
I'm using Stationery 1.0.0 with Thunderbird 60.2.1 (on Ubuntu 18.04.1). The add-on appears to be working correctly, but I cannot find a way to open the options. There isn't a "Stationery options" item in the Tools menu, there isn't a "Preferences" button for it in the Add-ons Manager screen, and there isn't an item for Stationery in the Add-ons Options menu (I believe this is the preferred place to open preferences for individual add-ons).

**Comment by blackcrack** [comment]
extras => Configuration/Options of Thunderbird | under this entry should you see in the pulldown menu,
very bottom ..

best regards
Blacky

**Comment by jefferyto** [comment]
Oh, I had the hidden the menu bar - I see "Stationery options" in the Tools menu in the menu bar. Thanks!

I usually keep the menu bar hidden and use the Thunderbird menu, opened by the toolbar menu button (right of the search box). It would be very helpful to be able to access the options from this menu as well.

**Comment by blackcrack** [comment]
Hi @jefferyto 
resolved ? (closing?)

best regards
Blacky

**Comment by jefferyto** [comment]
This is still an issue, especially for users like me that hide the menu bar. Adding an item to the Tools menu in the menu bar is non-standard.

The standard way for add-ons to make their options accessible is to add a menu item to the Addon Options menu in the Thunderbird menu, and to add a Preferences button to their entry in the Addons Manager page. According to the [Mozilla wiki](https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_57#Removed_and_changed_in_mozilla59), adding `<em:optionsURL>` back to install.rdf (and keeping `<em:optionsType>` removed) will accomplish this. (According to the [git history for install.rdf](https://github.com/arivald/tbirdExt/commit/0a43fa29db6ac766bdf1b7073bad246342421b58#diff-3d897739e1b847e6c32d66053f233ec4), both elements were removed in an update for Thunderbird 60.)

I can keep this issue open or close this and open a new issue. Which would you prefer @blackcrack?
